### ISSUE TITLE
Research Firebase. What could we use it for? Is it straightforward to set up for our project?

### ISSUE THREAD

**Issue by Tymotex** [csesoc/Structs.sh#39]

**Comment by amcunio** [comment]
|Service|Description|Use case|Useful?|
|----------|---------------|------------|-----------|
|Realtime database|An alternate NoSQL JSON database. There are javascript APIs for accessing the database. It is less versatile than MongoDB and can only be run in the cloud|Replace our MongoDB database|Probably not now that we have started with MongoDB|
|Remote config|A simpler way of managing an in-production app that allows for making changes quickly and rolling them out or rolling out changes to just a group of individuals||Not for our scale of app|
|Firebase ML|Machine learning features||No|
|Cloud functions|Runs a backend instance in the cloud using nodeJS so that a local backend is not required|Replaces the need for a backend|Depends if we want to run the backend ourselves but requires re-writing based on firebase events for functions to run|
|Authentication|Provides authentication services, including using third party services and manages the creation of user IDs (which is given back to the frontend)|Replace alternate authentication options|Not if we are going to authenticate with CSE (or we could use this alongside as an alternate authentication service for non-UNSW students)|
|Cloud messaging|Messaging service from server to users||No|
|Hosting|Deployment of app with CDNs||Depends on how we ultimately plan to deploy|
|Cloud storage|Storing user-generated data (like photos and videos)|Storing images and videos|Could be useful for images stored in lessons|

Generally cloudbase doesn't seem too hard to setup. There is clear documentation with full examples (https://firebase.google.com/docs/web/setup). They seem to be optimised for using multiple together, but can also be used individually.
